// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\{invoiceUuid}\disputes\{disputeUuid}\communications\{communicationUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCommunicationUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attachments property</summary>
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.AttachmentsRequestBuilder Attachments
        {
            get => new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.AttachmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.WithCommunicationUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommunicationUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes/{disputeUuid}/communications/{communicationUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.WithCommunicationUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCommunicationUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes/{disputeUuid}/communications/{communicationUuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
