// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses.Terminated;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v{version}\api\tenants\{tenantUuid}\invoices\{invoiceUuid}\statuses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The terminated property</summary>
        public global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses.Terminated.TerminatedRequestBuilder Terminated
        {
            get => new global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses.Terminated.TerminatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses.StatusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v{version}/api/tenants/{tenantUuid}/invoices/{invoiceUuid}/statuses", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.Item.Statuses.StatusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v{version}/api/tenants/{tenantUuid}/invoices/{invoiceUuid}/statuses", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
