// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v{version}\api\tenants\{tenantUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTenantUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The invoices property</summary>
        public global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.WithTenantUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v{version}/api/tenants/{tenantUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.VWithVersion.Api.Tenants.Item.WithTenantUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v{version}/api/tenants/{tenantUuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
