// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.V1;
using Navix.FreightAudit.Integration.V2;
using Navix.FreightAudit.Integration.VWithVersion;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration
{
    /// <summary>
    /// Builds and executes requests for operations under \integration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v1 property</summary>
        public global::Navix.FreightAudit.Integration.V1.V1RequestBuilder V1
        {
            get => new global::Navix.FreightAudit.Integration.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Navix.FreightAudit.Integration.V2.V2RequestBuilder V2
        {
            get => new global::Navix.FreightAudit.Integration.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.IntegrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.IntegrationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \integration\v{version}
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Integration.VWithVersion.VWithVersionRequestBuilder"/></returns>
        public global::Navix.FreightAudit.Integration.VWithVersion.VWithVersionRequestBuilder VWithVersion()
        {
            return new global::Navix.FreightAudit.Integration.VWithVersion.VWithVersionRequestBuilder(PathParameters, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
