// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Documents.Metadata.Item;
using Navix.FreightAudit.V2.Documents.Metadata.Orders;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Documents.Metadata
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\documents\metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetadataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The orders property</summary>
        public global::Navix.FreightAudit.V2.Documents.Metadata.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Navix.FreightAudit.V2.Documents.Metadata.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Navix.FreightAudit.v2.documents.metadata.item collection</summary>
        /// <param name="position">(Required) The UUID of the document.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("documentUuid", position);
                return new global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Navix.FreightAudit.v2.documents.metadata.item collection</summary>
        /// <param name="position">(Required) The UUID of the document.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("documentUuid", position);
                return new global::Navix.FreightAudit.V2.Documents.Metadata.Item.WithDocumentUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents/metadata", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.MetadataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MetadataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents/metadata", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
