// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Documents.Approved;
using Navix.FreightAudit.V2.Documents.Metadata;
using Navix.FreightAudit.V2.Documents.Orders;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Documents
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\documents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The approved property</summary>
        public global::Navix.FreightAudit.V2.Documents.Approved.ApprovedRequestBuilder Approved
        {
            get => new global::Navix.FreightAudit.V2.Documents.Approved.ApprovedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::Navix.FreightAudit.V2.Documents.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::Navix.FreightAudit.V2.Documents.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Navix.FreightAudit.V2.Documents.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Navix.FreightAudit.V2.Documents.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.DocumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.DocumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
