// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\{invoiceUuid}\disputes\{disputeUuid}\communications\{communicationUuid}\attachments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AttachmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Navix.FreightAudit.v2.invoices.item.disputes.item.communications.item.attachments.item collection</summary>
        /// <param name="position">(Required) The identifier should be the name of the attachment.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.Item.WithIdentifierItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.Item.WithIdentifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("identifier", position);
                return new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.Item.WithIdentifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.AttachmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AttachmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes/{disputeUuid}/communications/{communicationUuid}/attachments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.Communications.Item.Attachments.AttachmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AttachmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes/{disputeUuid}/communications/{communicationUuid}/attachments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
