// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v1\api\tenants\{tenantUuid}\vendor-invoices\{vendorInvoiceUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVendorInvoiceUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The documents property</summary>
        public global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVendorInvoiceUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices/{vendorInvoiceUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVendorInvoiceUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices/{vendorInvoiceUuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
