// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models.Invoice.Application.Models.Enums
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VendorInvoiceDocumentTypesEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Invoice")]
        #pragma warning disable CS1591
        Invoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryReceipt")]
        #pragma warning disable CS1591
        DeliveryReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "ProofOfDelivery")]
        #pragma warning disable CS1591
        ProofOfDelivery,
        #pragma warning restore CS1591
        [EnumMember(Value = "BillOfLading")]
        #pragma warning disable CS1591
        BillOfLading,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoticeOfAssignment")]
        #pragma warning disable CS1591
        NoticeOfAssignment,
        #pragma warning restore CS1591
        [EnumMember(Value = "RateConfirmation")]
        #pragma warning disable CS1591
        RateConfirmation,
        #pragma warning restore CS1591
        [EnumMember(Value = "WeightAndInspectionCertificate")]
        #pragma warning disable CS1591
        WeightAndInspectionCertificate,
        #pragma warning restore CS1591
        [EnumMember(Value = "LetterOfAuthority")]
        #pragma warning disable CS1591
        LetterOfAuthority,
        #pragma warning restore CS1591
        [EnumMember(Value = "LumperReceipt")]
        #pragma warning disable CS1591
        LumperReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "PackingList")]
        #pragma warning disable CS1591
        PackingList,
        #pragma warning restore CS1591
        [EnumMember(Value = "GeneratedInvoice")]
        #pragma warning disable CS1591
        GeneratedInvoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "Email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "CommercialInvoice")]
        #pragma warning disable CS1591
        CommercialInvoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "CertificateOfOrigin")]
        #pragma warning disable CS1591
        CertificateOfOrigin,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerRateConfirmation")]
        #pragma warning disable CS1591
        CustomerRateConfirmation,
        #pragma warning restore CS1591
        [EnumMember(Value = "ElectronicInterchangeReceipt")]
        #pragma warning disable CS1591
        ElectronicInterchangeReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "GatePass")]
        #pragma warning disable CS1591
        GatePass,
        #pragma warning restore CS1591
        [EnumMember(Value = "InsuranceCertificate")]
        #pragma warning disable CS1591
        InsuranceCertificate,
        #pragma warning restore CS1591
        [EnumMember(Value = "OtherReceipt")]
        #pragma warning disable CS1591
        OtherReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "W9")]
        #pragma warning disable CS1591
        W9,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryOrder")]
        #pragma warning disable CS1591
        DeliveryOrder,
        #pragma warning restore CS1591
        [EnumMember(Value = "WeightScaleTicket")]
        #pragma warning disable CS1591
        WeightScaleTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "TrailerInterchangeReceipt")]
        #pragma warning disable CS1591
        TrailerInterchangeReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "PurchaseOrder")]
        #pragma warning disable CS1591
        PurchaseOrder,
        #pragma warning restore CS1591
        [EnumMember(Value = "EscortTicket")]
        #pragma warning disable CS1591
        EscortTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "PermitReceipt")]
        #pragma warning disable CS1591
        PermitReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "ServiceOrder")]
        #pragma warning disable CS1591
        ServiceOrder,
        #pragma warning restore CS1591
        [EnumMember(Value = "CertificateOfDestruction")]
        #pragma warning disable CS1591
        CertificateOfDestruction,
        #pragma warning restore CS1591
        [EnumMember(Value = "DonationReceipt")]
        #pragma warning disable CS1591
        DonationReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "SmartAndFinalStamp")]
        #pragma warning disable CS1591
        SmartAndFinalStamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "InboundTripReport")]
        #pragma warning disable CS1591
        InboundTripReport,
        #pragma warning restore CS1591
        [EnumMember(Value = "WeighmasterCertificate")]
        #pragma warning disable CS1591
        WeighmasterCertificate,
        #pragma warning restore CS1591
        [EnumMember(Value = "CargoActivitySheet")]
        #pragma warning disable CS1591
        CargoActivitySheet,
        #pragma warning restore CS1591
        [EnumMember(Value = "WeberBOL")]
        #pragma warning disable CS1591
        WeberBOL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TimeCard")]
        #pragma warning disable CS1591
        TimeCard,
        #pragma warning restore CS1591
        [EnumMember(Value = "TransferSheet")]
        #pragma warning disable CS1591
        TransferSheet,
        #pragma warning restore CS1591
        [EnumMember(Value = "TripManifest")]
        #pragma warning disable CS1591
        TripManifest,
        #pragma warning restore CS1591
        [EnumMember(Value = "TrailerControlRecord")]
        #pragma warning disable CS1591
        TrailerControlRecord,
        #pragma warning restore CS1591
        [EnumMember(Value = "TargetTripSheet")]
        #pragma warning disable CS1591
        TargetTripSheet,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExitPass")]
        #pragma warning disable CS1591
        ExitPass,
        #pragma warning restore CS1591
        [EnumMember(Value = "PortOfArthurBOL")]
        #pragma warning disable CS1591
        PortOfArthurBOL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ColdChainCustodyForm")]
        #pragma warning disable CS1591
        ColdChainCustodyForm,
        #pragma warning restore CS1591
        [EnumMember(Value = "IGFFreightDispatch")]
        #pragma warning disable CS1591
        IGFFreightDispatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "EquipmentSubmissionForm")]
        #pragma warning disable CS1591
        EquipmentSubmissionForm,
        #pragma warning restore CS1591
        [EnumMember(Value = "Release")]
        #pragma warning disable CS1591
        Release,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACIManifest")]
        #pragma warning disable CS1591
        ACIManifest,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShipTicket")]
        #pragma warning disable CS1591
        ShipTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeliveryTicket")]
        #pragma warning disable CS1591
        DeliveryTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "InvoiceCorrected")]
        #pragma warning disable CS1591
        InvoiceCorrected,
        #pragma warning restore CS1591
        [EnumMember(Value = "EIRTicket")]
        #pragma warning disable CS1591
        EIRTicket,
        #pragma warning restore CS1591
        [EnumMember(Value = "PalletReceipt")]
        #pragma warning disable CS1591
        PalletReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "HistoricalAuditDocuments")]
        #pragma warning disable CS1591
        HistoricalAuditDocuments,
        #pragma warning restore CS1591
        [EnumMember(Value = "DetentionReceipt")]
        #pragma warning disable CS1591
        DetentionReceipt,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "Manifest")]
        #pragma warning disable CS1591
        Manifest,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerRateApproval")]
        #pragma warning disable CS1591
        CustomerRateApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "LoadCoverSheet")]
        #pragma warning disable CS1591
        LoadCoverSheet,
        #pragma warning restore CS1591
        [EnumMember(Value = "SafetyChecklist")]
        #pragma warning disable CS1591
        SafetyChecklist,
        #pragma warning restore CS1591
        [EnumMember(Value = "WalmartDeliveryConfirmationReport")]
        #pragma warning disable CS1591
        WalmartDeliveryConfirmationReport,
        #pragma warning restore CS1591
        [EnumMember(Value = "StatementInvoice")]
        #pragma warning disable CS1591
        StatementInvoice,
        #pragma warning restore CS1591
    }
}
