// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item.Result;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v2\api\tenants\{tenantUuid}\composite-vendor-invoices\{vendorInvoiceUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVendorInvoiceUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The result property</summary>
        public global::Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item.Result.ResultRequestBuilder Result
        {
            get => new global::Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item.Result.ResultRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVendorInvoiceUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v2/api/tenants/{tenantUuid}/composite-vendor-invoices/{vendorInvoiceUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V2.Api.Tenants.Item.CompositeVendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVendorInvoiceUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v2/api/tenants/{tenantUuid}/composite-vendor-invoices/{vendorInvoiceUuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
