// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Models;
using Navix.FreightAudit.V2.Invoices.Item.Disputes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Navix.FreightAudit.V2.Invoices.Item.Disputes
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\{invoiceUuid}\disputes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DisputesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Navix.FreightAudit.v2.invoices.item.disputes.item collection</summary>
        /// <param name="position">(Required) The UUID of the dispute.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("disputeUuid", position);
                return new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Navix.FreightAudit.v2.invoices.item.disputes.item collection</summary>
        /// <param name="position">(Required) The UUID of the dispute.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("disputeUuid", position);
                return new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.Item.WithDisputeUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisputesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisputesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/disputes", rawUrl)
        {
        }
        /// <summary>
        /// This returns the complete list of disputes on a single invoice. It&apos;s assumed that the total number of disputes is relatively small, so there&apos;s no paging, filtering, etc. Note that communications are not included, those must be retrieved separately.Note that the list is returned in an undefined order.A dispute is associated with a single party. However, there may be multiple reasons for a single dispute, and they may be created or resolved at different times.
        /// </summary>
        /// <returns>A List&lt;global::Navix.FreightAudit.Models.DisputeResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Navix.FreightAudit.Models.DisputeResponse>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Navix.FreightAudit.Models.DisputeResponse>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Navix.FreightAudit.Models.DisputeResponse>(requestInfo, global::Navix.FreightAudit.Models.DisputeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// This returns the complete list of disputes on a single invoice. It&apos;s assumed that the total number of disputes is relatively small, so there&apos;s no paging, filtering, etc. Note that communications are not included, those must be retrieved separately.Note that the list is returned in an undefined order.A dispute is associated with a single party. However, there may be multiple reasons for a single dispute, and they may be created or resolved at different times.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DisputesRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
