// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Invoices.Item.Documents.Item.FileNamespace;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Invoices.Item.Documents.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\{invoiceUuid}\documents\{documentUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDocumentUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The file property</summary>
        public global::Navix.FreightAudit.V2.Invoices.Item.Documents.Item.FileNamespace.FileRequestBuilder File
        {
            get => new global::Navix.FreightAudit.V2.Invoices.Item.Documents.Item.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Documents.Item.WithDocumentUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocumentUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/documents/{documentUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.Documents.Item.WithDocumentUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDocumentUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}/documents/{documentUuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
