// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Invoices.Lookup.External;
using Navix.FreightAudit.V2.Invoices.Lookup.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Invoices.Lookup
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\lookup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LookupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The external property</summary>
        public global::Navix.FreightAudit.V2.Invoices.Lookup.External.ExternalRequestBuilder External
        {
            get => new global::Navix.FreightAudit.V2.Invoices.Lookup.External.ExternalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Navix.FreightAudit.v2.invoices.lookup.item collection</summary>
        /// <param name="position">(Required) The UUID of the invoice.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("invoiceUuid", position);
                return new global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Navix.FreightAudit.v2.invoices.lookup.item collection</summary>
        /// <param name="position">(Required) The UUID of the invoice.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("invoiceUuid", position);
                return new global::Navix.FreightAudit.V2.Invoices.Lookup.Item.WithInvoiceUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/lookup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Lookup.LookupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LookupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/lookup", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
