// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v1\api\tenants\{tenantUuid}\vendor-invoices
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VendorInvoicesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Navix.FreightAudit.integration.v1.api.tenants.item.vendorInvoices.item collection</summary>
        /// <param name="position">The UUID of the vendor invoice who owns the document</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vendorInvoiceUuid", position);
                return new global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Navix.FreightAudit.integration.v1.api.tenants.item.vendorInvoices.item collection</summary>
        /// <param name="position">The UUID of the vendor invoice who owns the document</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("vendorInvoiceUuid", position);
                return new global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.WithVendorInvoiceUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.VendorInvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VendorInvoicesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.VendorInvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VendorInvoicesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
