// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.Models;
using Navix.FreightAudit.V2.Invoices.Item.Disputes;
using Navix.FreightAudit.V2.Invoices.Item.Documents;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Navix.FreightAudit.V2.Invoices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\invoices\{invoiceUuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithInvoiceUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The disputes property</summary>
        public global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder Disputes
        {
            get => new global::Navix.FreightAudit.V2.Invoices.Item.Disputes.DisputesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The documents property</summary>
        public global::Navix.FreightAudit.V2.Invoices.Item.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Navix.FreightAudit.V2.Invoices.Item.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.WithInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInvoiceUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Invoices.Item.WithInvoiceUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInvoiceUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/invoices/{invoiceUuid}", rawUrl)
        {
        }
        /// <summary>
        /// This returns an invoice. Unlike the &apos;Get Audit Results&apos; endpoint, this can be used to return an invoice that&apos;s in any state, including one that hasn&apos;t been approved or terminated.This endpoint takes a UUID. If you know the invoice&apos;s External Id, but not it&apos;s UUID, use the &apos;Get Invoice Uuid&apos; endpoint first to translate the External Id to a UUID.
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.VendorInvoicePublicDto"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Navix.FreightAudit.Models.BadRequestResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Navix.FreightAudit.Models.VendorInvoicePublicDto?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Navix.FreightAudit.Models.VendorInvoicePublicDto> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Navix.FreightAudit.Models.BadRequestResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Navix.FreightAudit.Models.VendorInvoicePublicDto>(requestInfo, global::Navix.FreightAudit.Models.VendorInvoicePublicDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This returns an invoice. Unlike the &apos;Get Audit Results&apos; endpoint, this can be used to return an invoice that&apos;s in any state, including one that hasn&apos;t been approved or terminated.This endpoint takes a UUID. If you know the invoice&apos;s External Id, but not it&apos;s UUID, use the &apos;Get Invoice Uuid&apos; endpoint first to translate the External Id to a UUID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Invoices.Item.WithInvoiceUuItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Navix.FreightAudit.V2.Invoices.Item.WithInvoiceUuItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Navix.FreightAudit.V2.Invoices.Item.WithInvoiceUuItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithInvoiceUuItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
