// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Pre.Documents;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Pre
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\pre
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The documents property</summary>
        public global::Navix.FreightAudit.V2.Pre.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Navix.FreightAudit.V2.Pre.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Pre.PreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/pre", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Pre.PreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/pre", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
