// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The party to which the dispute applies</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DisputeResponse_party
    {
        [EnumMember(Value = "Vendor")]
        #pragma warning disable CS1591
        Vendor,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tenant")]
        #pragma warning disable CS1591
        Tenant,
        #pragma warning restore CS1591
        [EnumMember(Value = "Customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
    }
}
