// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Navix.FreightAudit.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DocumentResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approvedAt property</summary>
        public DateTimeOffset? ApprovedAt { get; set; }
        /// <summary>The approvedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovedBy { get; set; }
#nullable restore
#else
        public string ApprovedBy { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The hasSignature property</summary>
        public bool? HasSignature { get; set; }
        /// <summary>The orderExternalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderExternalId { get; set; }
#nullable restore
#else
        public string OrderExternalId { get; set; }
#endif
        /// <summary>The orderStopSequence property</summary>
        public int? OrderStopSequence { get; set; }
        /// <summary>The status property</summary>
        public global::Navix.FreightAudit.Models.DocumentResponse_status? Status { get; set; }
        /// <summary>The type property</summary>
        public global::Navix.FreightAudit.Models.DocumentResponse_type? Type { get; set; }
        /// <summary>The uuid property</summary>
        public Guid? Uuid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Models.DocumentResponse"/> and sets the default values.
        /// </summary>
        public DocumentResponse()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Navix.FreightAudit.Models.DocumentResponse_status.Draft;
            Type = global::Navix.FreightAudit.Models.DocumentResponse_type.Unset;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.DocumentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Navix.FreightAudit.Models.DocumentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Navix.FreightAudit.Models.DocumentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approvedAt", n => { ApprovedAt = n.GetDateTimeOffsetValue(); } },
                { "approvedBy", n => { ApprovedBy = n.GetStringValue(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "hasSignature", n => { HasSignature = n.GetBoolValue(); } },
                { "orderExternalId", n => { OrderExternalId = n.GetStringValue(); } },
                { "orderStopSequence", n => { OrderStopSequence = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Navix.FreightAudit.Models.DocumentResponse_status>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Navix.FreightAudit.Models.DocumentResponse_type>(); } },
                { "uuid", n => { Uuid = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("approvedAt", ApprovedAt);
            writer.WriteStringValue("approvedBy", ApprovedBy);
            writer.WriteStringValue("filename", Filename);
            writer.WriteBoolValue("hasSignature", HasSignature);
            writer.WriteStringValue("orderExternalId", OrderExternalId);
            writer.WriteIntValue("orderStopSequence", OrderStopSequence);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.DocumentResponse_status>("status", Status);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.DocumentResponse_type>("type", Type);
            writer.WriteGuidValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
