// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The invoice type. Defaults to &apos;Invoice&apos; when empty.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceRequest_type
    {
        [EnumMember(Value = "Invoice")]
        #pragma warning disable CS1591
        Invoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "BalanceDue")]
        #pragma warning disable CS1591
        BalanceDue,
        #pragma warning restore CS1591
        [EnumMember(Value = "Supplemental")]
        #pragma warning disable CS1591
        Supplemental,
        #pragma warning restore CS1591
    }
}
