// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The Reference Number type. Defaults to &apos;GeneralReferenceNumber&apos; when empty.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceReferenceNumberRequest_type
    {
        [EnumMember(Value = "GeneralReferenceNumber")]
        #pragma warning disable CS1591
        GeneralReferenceNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "OrderNumber")]
        #pragma warning disable CS1591
        OrderNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOLNumber")]
        #pragma warning disable CS1591
        BOLNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "PONumber")]
        #pragma warning disable CS1591
        PONumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "SONumber")]
        #pragma warning disable CS1591
        SONumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "ShipmentNumber")]
        #pragma warning disable CS1591
        ShipmentNumber,
        #pragma warning restore CS1591
    }
}
