// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The Item handling unit</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceItemRequest_handlingUnit
    {
        [EnumMember(Value = "Pallet")]
        #pragma warning disable CS1591
        Pallet,
        #pragma warning restore CS1591
        [EnumMember(Value = "Drum")]
        #pragma warning disable CS1591
        Drum,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bag")]
        #pragma warning disable CS1591
        Bag,
        #pragma warning restore CS1591
        [EnumMember(Value = "Barrels")]
        #pragma warning disable CS1591
        Barrels,
        #pragma warning restore CS1591
        [EnumMember(Value = "Crates")]
        #pragma warning disable CS1591
        Crates,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bundles")]
        #pragma warning disable CS1591
        Bundles,
        #pragma warning restore CS1591
        [EnumMember(Value = "Piece")]
        #pragma warning disable CS1591
        Piece,
        #pragma warning restore CS1591
        [EnumMember(Value = "Loose")]
        #pragma warning disable CS1591
        Loose,
        #pragma warning restore CS1591
        [EnumMember(Value = "Boxes")]
        #pragma warning disable CS1591
        Boxes,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cases")]
        #pragma warning disable CS1591
        Cases,
        #pragma warning restore CS1591
        [EnumMember(Value = "Carton")]
        #pragma warning disable CS1591
        Carton,
        #pragma warning restore CS1591
        [EnumMember(Value = "Totes")]
        #pragma warning disable CS1591
        Totes,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cans")]
        #pragma warning disable CS1591
        Cans,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cylinders")]
        #pragma warning disable CS1591
        Cylinders,
        #pragma warning restore CS1591
        [EnumMember(Value = "FlatRacks")]
        #pragma warning disable CS1591
        FlatRacks,
        #pragma warning restore CS1591
        [EnumMember(Value = "Kegs")]
        #pragma warning disable CS1591
        Kegs,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pails")]
        #pragma warning disable CS1591
        Pails,
        #pragma warning restore CS1591
        [EnumMember(Value = "Reels")]
        #pragma warning disable CS1591
        Reels,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rolls")]
        #pragma warning disable CS1591
        Rolls,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tanks")]
        #pragma warning disable CS1591
        Tanks,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tubes")]
        #pragma warning disable CS1591
        Tubes,
        #pragma warning restore CS1591
    }
}
