// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Navix.FreightAudit.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InvoiceItemRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Item freight class. Accepted values: 50, 55, 60, 65, 70, 77.5, 85, 92.5, 100, 110, 125, 150, 175, 200, 250, 300, 400, 500  </summary>
        public double? Class { get; set; }
        /// <summary>The Item description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The physical dimensions of the Item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.InvoiceItemDimensionRequest? Dimensions { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.InvoiceItemDimensionRequest Dimensions { get; set; }
#endif
        /// <summary>The Item handling unit</summary>
        public global::Navix.FreightAudit.Models.InvoiceItemRequest_handlingUnit? HandlingUnit { get; set; }
        /// <summary>The quantity, in handling units</summary>
        public int? HandlingUnitCount { get; set; }
        /// <summary>The unique identifier for the Item. This item Id can be used to set a charge as a Base Rate type in Navix, see below Charges section (charge.itemId) for this endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The Item NMFC code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NmfcCode { get; set; }
#nullable restore
#else
        public string NmfcCode { get; set; }
#endif
        /// <summary>The total quantity</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Models.InvoiceItemRequest"/> and sets the default values.
        /// </summary>
        public InvoiceItemRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.InvoiceItemRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Navix.FreightAudit.Models.InvoiceItemRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Navix.FreightAudit.Models.InvoiceItemRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "class", n => { Class = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dimensions", n => { Dimensions = n.GetObjectValue<global::Navix.FreightAudit.Models.InvoiceItemDimensionRequest>(global::Navix.FreightAudit.Models.InvoiceItemDimensionRequest.CreateFromDiscriminatorValue); } },
                { "handlingUnit", n => { HandlingUnit = n.GetEnumValue<global::Navix.FreightAudit.Models.InvoiceItemRequest_handlingUnit>(); } },
                { "handlingUnitCount", n => { HandlingUnitCount = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "nmfcCode", n => { NmfcCode = n.GetStringValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("class", Class);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.InvoiceItemDimensionRequest>("dimensions", Dimensions);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.InvoiceItemRequest_handlingUnit>("handlingUnit", HandlingUnit);
            writer.WriteIntValue("handlingUnitCount", HandlingUnitCount);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("nmfcCode", NmfcCode);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
