// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The unit type for calculated charges (e.g., PerMile, PerHour, PerPallet). Required when Charge is not provided. Must be used with Rate and Quantity. Defines what the Rate and Quantity represent for charge calculation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceChargeRequest_qualifier
    {
        [EnumMember(Value = "PerPound")]
        #pragma warning disable CS1591
        PerPound,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerHundredweight")]
        #pragma warning disable CS1591
        PerHundredweight,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerTon")]
        #pragma warning disable CS1591
        PerTon,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerMile")]
        #pragma warning disable CS1591
        PerMile,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerKilometer")]
        #pragma warning disable CS1591
        PerKilometer,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerHour")]
        #pragma warning disable CS1591
        PerHour,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerCase")]
        #pragma warning disable CS1591
        PerCase,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerPallet")]
        #pragma warning disable CS1591
        PerPallet,
        #pragma warning restore CS1591
        [EnumMember(Value = "PerUnit")]
        #pragma warning disable CS1591
        PerUnit,
        #pragma warning restore CS1591
        [EnumMember(Value = "Percent")]
        #pragma warning disable CS1591
        Percent,
        #pragma warning restore CS1591
    }
}
