// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Navix.FreightAudit.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderVendorRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The physical address of the Stop</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderAddressRequest? Address { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderAddressRequest Address { get; set; }
#endif
        /// <summary>The physical address of the Stop</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderAddressRequest? BillToAddress { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderAddressRequest BillToAddress { get; set; }
#endif
        /// <summary>The list of Charge Codes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Navix.FreightAudit.Models.OrderChargeRequest>? Charges { get; set; }
#nullable restore
#else
        public List<global::Navix.FreightAudit.Models.OrderChargeRequest> Charges { get; set; }
#endif
        /// <summary>The freight payment terms. Defaults to &apos;ThirdParty&apos; when empty.</summary>
        public global::Navix.FreightAudit.Models.OrderVendorRequest_chargeTerms? ChargeTerms { get; set; }
        /// <summary>The contact information of the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderContactRequest? Contact { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderContactRequest Contact { get; set; }
#endif
        /// <summary>The three character ISO 4217 code for the Vendor Currency. Defaults to &apos;USD&apos; when empty.</summary>
        public global::Navix.FreightAudit.Models.OrderVendorRequest_currency? Currency { get; set; }
        /// <summary>The DOT Number for the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DotNumber { get; set; }
#nullable restore
#else
        public string DotNumber { get; set; }
#endif
        /// <summary>The Tenant&apos;s unique identifier for the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The MC Number for the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? McNumber { get; set; }
#nullable restore
#else
        public string McNumber { get; set; }
#endif
        /// <summary>The Name of the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The payment terms for the Vendor</summary>
        public global::Navix.FreightAudit.Models.OrderVendorRequest_paymentTerms? PaymentTerms { get; set; }
        /// <summary>The physical address of the Stop</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderAddressRequest? RemitToAddress { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderAddressRequest RemitToAddress { get; set; }
#endif
        /// <summary>The Standard Carrier Alpha Code for the Vendor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScacCode { get; set; }
#nullable restore
#else
        public string ScacCode { get; set; }
#endif
        /// <summary>The Service information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderServiceRequest? Service { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderServiceRequest Service { get; set; }
#endif
        /// <summary>The Type of the Vendor</summary>
        public global::Navix.FreightAudit.Models.OrderVendorRequest_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Models.OrderVendorRequest"/> and sets the default values.
        /// </summary>
        public OrderVendorRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.OrderVendorRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Navix.FreightAudit.Models.OrderVendorRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Navix.FreightAudit.Models.OrderVendorRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>(global::Navix.FreightAudit.Models.OrderAddressRequest.CreateFromDiscriminatorValue); } },
                { "billToAddress", n => { BillToAddress = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>(global::Navix.FreightAudit.Models.OrderAddressRequest.CreateFromDiscriminatorValue); } },
                { "chargeTerms", n => { ChargeTerms = n.GetEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_chargeTerms>(); } },
                { "charges", n => { Charges = n.GetCollectionOfObjectValues<global::Navix.FreightAudit.Models.OrderChargeRequest>(global::Navix.FreightAudit.Models.OrderChargeRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contact", n => { Contact = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderContactRequest>(global::Navix.FreightAudit.Models.OrderContactRequest.CreateFromDiscriminatorValue); } },
                { "currency", n => { Currency = n.GetEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_currency>(); } },
                { "dotNumber", n => { DotNumber = n.GetStringValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "mcNumber", n => { McNumber = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "paymentTerms", n => { PaymentTerms = n.GetEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_paymentTerms>(); } },
                { "remitToAddress", n => { RemitToAddress = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>(global::Navix.FreightAudit.Models.OrderAddressRequest.CreateFromDiscriminatorValue); } },
                { "scacCode", n => { ScacCode = n.GetStringValue(); } },
                { "service", n => { Service = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderServiceRequest>(global::Navix.FreightAudit.Models.OrderServiceRequest.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>("address", Address);
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>("billToAddress", BillToAddress);
            writer.WriteCollectionOfObjectValues<global::Navix.FreightAudit.Models.OrderChargeRequest>("charges", Charges);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_chargeTerms>("chargeTerms", ChargeTerms);
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderContactRequest>("contact", Contact);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_currency>("currency", Currency);
            writer.WriteStringValue("dotNumber", DotNumber);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("mcNumber", McNumber);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_paymentTerms>("paymentTerms", PaymentTerms);
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>("remitToAddress", RemitToAddress);
            writer.WriteStringValue("scacCode", ScacCode);
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderServiceRequest>("service", Service);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.OrderVendorRequest_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
