// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The transportation mode</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderServiceRequest_mode
    {
        [EnumMember(Value = "Ground")]
        #pragma warning disable CS1591
        Ground,
        #pragma warning restore CS1591
        [EnumMember(Value = "Air")]
        #pragma warning disable CS1591
        Air,
        #pragma warning restore CS1591
        [EnumMember(Value = "NonFreight")]
        #pragma warning disable CS1591
        NonFreight,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ocean")]
        #pragma warning disable CS1591
        Ocean,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rail")]
        #pragma warning disable CS1591
        Rail,
        #pragma warning restore CS1591
    }
}
