// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The type of Stop</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderStopRequest_type
    {
        [EnumMember(Value = "Origin")]
        #pragma warning disable CS1591
        Origin,
        #pragma warning restore CS1591
        [EnumMember(Value = "Destination")]
        #pragma warning disable CS1591
        Destination,
        #pragma warning restore CS1591
    }
}
