// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The Type of the Vendor</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderVendorRequest_type
    {
        [EnumMember(Value = "Carrier")]
        #pragma warning disable CS1591
        Carrier,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warehouse")]
        #pragma warning disable CS1591
        Warehouse,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
