// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The role of the contact</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderInternalContactRequest_role
    {
        [EnumMember(Value = "Broker")]
        #pragma warning disable CS1591
        Broker,
        #pragma warning restore CS1591
        [EnumMember(Value = "CarrierSales")]
        #pragma warning disable CS1591
        CarrierSales,
        #pragma warning restore CS1591
        [EnumMember(Value = "AR")]
        #pragma warning disable CS1591
        AR,
        #pragma warning restore CS1591
        [EnumMember(Value = "AP")]
        #pragma warning disable CS1591
        AP,
        #pragma warning restore CS1591
    }
}
