// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The freight payment terms. Defaults to &apos;ThirdParty&apos; when empty.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderVendorRequest_chargeTerms
    {
        [EnumMember(Value = "Collect")]
        #pragma warning disable CS1591
        Collect,
        #pragma warning restore CS1591
        [EnumMember(Value = "Prepaid")]
        #pragma warning disable CS1591
        Prepaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrepaidAdd")]
        #pragma warning disable CS1591
        PrepaidAdd,
        #pragma warning restore CS1591
        [EnumMember(Value = "ThirdParty")]
        #pragma warning disable CS1591
        ThirdParty,
        #pragma warning restore CS1591
    }
}
