// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Navix.FreightAudit.Models
{
    /// <summary>The three character ISO 3166-1 alpha 3 code for the country. Defaults to &apos;USA&apos; when empty.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderAddressRequest_country
    {
        [EnumMember(Value = "USA")]
        #pragma warning disable CS1591
        USA,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAN")]
        #pragma warning disable CS1591
        CAN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEX")]
        #pragma warning disable CS1591
        MEX,
        #pragma warning restore CS1591
    }
}
