// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Navix.FreightAudit.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderStopRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The physical address of the Stop</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Navix.FreightAudit.Models.OrderAddressRequest? Address { get; set; }
#nullable restore
#else
        public global::Navix.FreightAudit.Models.OrderAddressRequest Address { get; set; }
#endif
        /// <summary>The Stop sequence</summary>
        public int? Sequence { get; set; }
        /// <summary>The type of Stop</summary>
        public global::Navix.FreightAudit.Models.OrderStopRequest_type? Type { get; set; }
        /// <summary>If you are not handling customer charges in Navix, and sending in a multimodal Navix Order with multi-segments/movements/legs, you can associate a vendor to the specific stop. Please view payload example of what we recommend.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Vendors { get; set; }
#nullable restore
#else
        public List<string> Vendors { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Models.OrderStopRequest"/> and sets the default values.
        /// </summary>
        public OrderStopRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.OrderStopRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Navix.FreightAudit.Models.OrderStopRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Navix.FreightAudit.Models.OrderStopRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>(global::Navix.FreightAudit.Models.OrderAddressRequest.CreateFromDiscriminatorValue); } },
                { "sequence", n => { Sequence = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Navix.FreightAudit.Models.OrderStopRequest_type>(); } },
                { "vendors", n => { Vendors = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Navix.FreightAudit.Models.OrderAddressRequest>("address", Address);
            writer.WriteIntValue("sequence", Sequence);
            writer.WriteEnumValue<global::Navix.FreightAudit.Models.OrderStopRequest_type>("type", Type);
            writer.WriteCollectionOfPrimitiveValues<string>("vendors", Vendors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
