// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Attachment;
using Navix.FreightAudit.V2.Documents;
using Navix.FreightAudit.V2.Invoices;
using Navix.FreightAudit.V2.Orders;
using Navix.FreightAudit.V2.Pre;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attachment property</summary>
        public global::Navix.FreightAudit.V2.Attachment.AttachmentRequestBuilder Attachment
        {
            get => new global::Navix.FreightAudit.V2.Attachment.AttachmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The documents property</summary>
        public global::Navix.FreightAudit.V2.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Navix.FreightAudit.V2.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::Navix.FreightAudit.V2.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::Navix.FreightAudit.V2.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Navix.FreightAudit.V2.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Navix.FreightAudit.V2.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pre property</summary>
        public global::Navix.FreightAudit.V2.Pre.PreRequestBuilder Pre
        {
            get => new global::Navix.FreightAudit.V2.Pre.PreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
