// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Navix.FreightAudit.V2.Documents.Metadata.Orders.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Navix.FreightAudit.V2.Documents.Metadata.Orders
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\documents\metadata\orders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Navix.FreightAudit.v2.documents.metadata.orders.item collection</summary>
        /// <param name="position">(Required) The Order External Id of the Order.</param>
        /// <returns>A <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.Orders.Item.WithOrderExternalItemRequestBuilder"/></returns>
        public global::Navix.FreightAudit.V2.Documents.Metadata.Orders.Item.WithOrderExternalItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orderExternalId", position);
                return new global::Navix.FreightAudit.V2.Documents.Metadata.Orders.Item.WithOrderExternalItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents/metadata/orders", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.V2.Documents.Metadata.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/documents/metadata/orders", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
