// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Navix.FreightAudit.Models.Invoice.Models.Responses
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FinalizedInvoicePaginationResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currentPage property</summary>
        public int? CurrentPage { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoiceResponse>? Records { get; set; }
#nullable restore
#else
        public List<global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoiceResponse> Records { get; set; }
#endif
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>The totalRecords property</summary>
        public int? TotalRecords { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoicePaginationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoicePaginationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoicePaginationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPage", n => { CurrentPage = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "records", n => { Records = n.GetCollectionOfObjectValues<global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoiceResponse>(global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoiceResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
                { "totalRecords", n => { TotalRecords = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPage", CurrentPage);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteCollectionOfObjectValues<global::Navix.FreightAudit.Models.Invoice.Models.Responses.FinalizedInvoiceResponse>("records", Records);
            writer.WriteIntValue("totalPages", TotalPages);
            writer.WriteIntValue("totalRecords", TotalRecords);
        }
    }
}
#pragma warning restore CS0618
