// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \integration\v1\api\tenants\{tenantUuid}\vendor-invoices\{vendorInvoiceUuid}\documents\{documentUuid}\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices/{vendorInvoiceUuid}/documents/{documentUuid}/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/integration/v1/api/tenants/{tenantUuid}/vendor-invoices/{vendorInvoiceUuid}/documents/{documentUuid}/download", rawUrl)
        {
        }
        /// <summary>
        /// Returns the raw binary file of a document associated with an invoice. The `Content-Type` header will contain the MIME type of the file, such as `application/pdf`. The`Content-Disposition` header will contain the original name of the file (such as the filename in the email that was sent to Navix).This is intended to be used after a call to the &quot;Get Audit Result&quot; endpoint. The UUIDs for documents can be found in the returned payload from &quot;Get Audit Results&quot;, under`orders.documents`.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the raw binary file of a document associated with an invoice. The `Content-Type` header will contain the MIME type of the file, such as `application/pdf`. The`Content-Disposition` header will contain the original name of the file (such as the filename in the email that was sent to Navix).This is intended to be used after a call to the &quot;Get Audit Result&quot; endpoint. The UUIDs for documents can be found in the returned payload from &quot;Get Audit Results&quot;, under`orders.documents`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download.DownloadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download.DownloadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Navix.FreightAudit.Integration.V1.Api.Tenants.Item.VendorInvoices.Item.Documents.Item.Download.DownloadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
